### PR TITLE
WIP: Patch up errors

### PR DESCRIPTION
**Pull request by im-coder-lg**
You can thank me later, buddy :)

Just wait and watch the errors go, I will show the mistake that happened, so that you don't have to repeat that.

Your Gemfile has the `gemspec` line, which does the job, why add other lines?

I'll fix this for ya

### CODE REVIEW

**Comment by im-coder-lg** [comment]
lemme test this on codespaces to make sure this works

**Comment by im-coder-lg** [comment]
okay eventmachine fail :/ testing via gitpod

Can you enable the checks to make sure this ain't a fail?

**Comment by im-coder-lg** [comment]
Your Ruby 3.0.0 build fails. Add the command `bundle lock {some_gibberish}` from [my output](https://github.com/im-coder-lg/kylereddoch.github.io/actions/runs/3282395762/jobs/5405744336).

**Comment by im-coder-lg** [comment]
And tada, brand new! Check the outputs from my workflows!

**Comment by kylereddoch** [comment]
Curious, on the gemfile, why did you remove
gem 'jekyll-sitemap'
gem 'github-pages'

I need those. Also, I want it as a remote theme that way I can just update the version number when the theme updates.

**Comment by im-coder-lg** [comment]
Well, yeah I added webrick and...

Wait what do you mean by you need github-pages? You are just deploying there, right?

Better add it into the spec file so that it doesn't crash. You can edit through this PR.

**Comment by im-coder-lg** [comment]
Plus, a few of the things added in the gemfile coincided with the specfile causing errors. That's why I removed it.

**Comment by kylereddoch** [comment]
Just merged it but the build still failed.

**Comment by kylereddoch** [comment]
Figured it out. I guess we need to check in our gem lock files now.

**Comment by im-coder-lg** [comment]
Yeah, if you face errors like those, just clone it locally, run `bundle install` and make sure it updates the gem file lock. Then recommit here and watch the build go green.

**Comment by im-coder-lg** [comment]
That is what happens in Node.js projects but this idea of build fails(lockfile not updated) makes more sense.

**Pull request merged**
